// Generated by CoffeeScript 1.12.7
(function() {
  
var app = app || {};
ENTER_KEY = 13;
  jQuery(document).ready(function() {
    var ENTER_KEY;
    ENTER_KEY = 13;
    return new AppView();
  });

}).call(this);
