// Generated by CoffeeScript 1.12.7
(function() {
  var app = app || {};
  this.TodoView = Backbone.View.extend({
    tagName: "li",
    template: _.template($("#item-template").html()),
    events: {
      "click .toggle": "toggleCompleted",
      "dblclick label": "edit",
      "click .destroy": "clear",
      "keypress .edit": "updateOnEnter",
      "blur .edit": "close"
    },
    initialize: function() {
      this.listenTo(this.model, "change", this.render);
      this.listenTo(this.model, "destroy", this.remove);
      return this.listenTo(this.model, "visible", this.toggleVisible);
    },
    render: function() {
      console.log("rendering todo");
      this.$el.html(this.template(this.model.attributes));
      this.$el.toggleClass("completed", this.model.get("completed"));
      this.toggleVisible();
      this.$input = this.$(".edit");
      return this;
    },
    toggleVisible: function() {
      return this.$el.toggleClass("hidden", this.isHidden());
    },
    isHidden: function() {
      var isCompleted;
      isCompleted = this.model.get("completed");
      return (!isCompleted && TodoFilter === "completed") || (isCompleted && TodoFilter === "active");
    },
    toggleCompleted: function() {
      return this.model.toggle();
    },
    edit: function() {
      console.log("now editing");
      this.$el.addClass("editing");
      this.$input.removeAttr("hidden");
      return this.$input.focus();
    },
    close: function() {
      var value;
      value = this.$input.val().trim();
      if (value) {
        this.model.save({
          title: value
        });
      } else {
        this.clear();
      }
      return this.$el.removeClass("editing");
    },
    updateOnEnter: function(e) {
      if (e.which === ENTER_KEY) {
        return this.close();
      }
    },
    clear: function() {
      return this.model.destroy();
    }
  });

}).call(this);
