// Generated by CoffeeScript 1.12.7
(function() {
  var app = app || {};
  this.Todo = Backbone.Model.extend({
    defaults: {
      title: '',
      completed: false
    },
    toggle: function() {
      return this.save({
        completed: !this.get('completed')
      });
    }
  });

}).call(this);
